spring.application.name=app


spring.datasource.url=jdbc:postgresql://localhost:5432/spring_database
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always

spring.sql.init.defer-datasource-initialization=true
server.ssl.enabled=false

spring.security.oauth2.client.registration.github.client-id=Ov23likD3oFl6PMAlna6
spring.security.oauth2.client.registration.github.client-secret=92e351d963d492c771e746a7862dfc57858359fa
spring.security.oauth2.client.registration.github.scope=read:user, user:email
spring.security.oauth2.client.provider.github.authorization-uri=https://github.com/login/oauth/authorize
spring.security.oauth2.client.provider.github.token-uri=https://github.com/login/oauth/access_token
spring.security.oauth2.client.provider.github.user-info-uri=https://api.github.com/user

logging.level.org.springframework.web.filter=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.thymeleaf: DEBUG





